# Generated by Django 6.0.5 on 2026-05-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title of the statement/question', max_length=200)),
                ('text', models.TextField(help_text='The actual statement the user can agree or disagree with')),
                ('mvp_position', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', help_text='The official position of the MVP party', max_length=7)),
                ('explanation', models.TextField(help_text='The background text explaining why the party chose this position')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='state.theme')),
            ],
            options={
                'verbose_name': 'statement',
                'verbose_name_plural': 'statements',
                'ordering': ['created_at'],
            },
        ),
    ]
